#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Aug 29, 2025 07:43:13 PM %z  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import fnaf

_debug = True # False to eliminate debug printing from callback functions.

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = fnaf.Toplevel1(_top1)
    root.mainloop()

def door1(*args):
    if _debug:
        print('fnaf_support.door1')
        for arg in args:
            print ('    another arg:', arg)
        sys.stdout.flush()
        fnaf.Toplevel1.door1main()

def door2(*args):
    if _debug:
        print('fnaf_support.door2')
        for arg in args:
            print ('    another arg:', arg)
        sys.stdout.flush()

if __name__ == '__main__':
    fnaf.start_up()




